---
# Per-host proměnné pro labkey-vav
# Přepisují hodnoty z group_vars/labkey_servers.yml

labkey_hostname: "labkey-vav.firma.cz"

ssl_cert_file: "labkey-vav.crt"
ssl_key_file:  "labkey-vav.key"

# Hesla specifická pro tento server (doporučeno: ansible-vault encrypt_string)
# labkey_db_pass:        "tajne_heslo_vav"
# labkey_encryption_key: "changeme32charslongkey12345678"
